apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: src
  name: src
spec:
  replicas: 1
  selector:
    app: src
  template:
    metadata:
      labels:
        app: src
    spec:
      containers:
      - image: registry.example.com:5000/openshift-udp-test
        imagePullPolicy: Always
        name: src
        command:
        - socat
        - -v
        - udp-l:8000,fork
        - exec:'/bin/cat'
  triggers:
  - type: ConfigChange
